const dataParts = [
    {partnumber:['MIO-7237'], partName:'LEV3 Shell', partEcl:'4',customer:'Stant',mould:"STA5A",documents:""},
    {partnumber:['MIO-7207'], partName:'ECE Cover', partEcl:'3',customer:'Stant',mould:"Sta2B",documents:""},
    {partnumber:['MIO-7238'], partName:'LEV3 Cover', partEcl:'5',customer:'Stant',mould:"STA2B",documents:""},
    {partnumber:['MIO-7203'], partName:'ECE Shell', partEcl:'2',customer:'Stant',mould:"STA1B",documents:""},


    {partnumber:['MX400607-HOU-FS'], partName:'Housing DJ Capless DSL - FS', partEcl:'1',customer:'Martinrea',mould:"MA08-M01-A",documents:""},
    {partnumber:['MX400608-HOU-FS'], partName:'Housing DJ Capless DSL - FS', partEcl:'1',customer:'Martinrea',mould:"MA08-M01-A",documents:""},
    {partnumber:['MX400607-HOU-SS'], partName:'Housing DJ Capless DSL - SS', partEcl:'1',customer:'Martinrea',mould:"MA08-M01-A",documents:""},
    {partnumber:['MX400608-HOU-SS'], partName:'Housing DJ Capless DSL - SS', partEcl:'1',customer:'Martinrea',mould:"MA08-M01-A",documents:""},
    {partnumber:['MX400607-TUB'], partName:'DJ Capless - Urea Tube', partEcl:'1',customer:'Martinrea',mould:"MA08-M03-A",documents:""},
    {partnumber:['MX400607-ADP'], partName:'DJ Capless - Blue Adaptor', partEcl:'1',customer:'Martinrea',mould:"MA08-M03-A",documents:""},
    {partnumber:['MX400607-TAA'], partName:'DJ Capless - Housing 1st Shot', partEcl:'1',customer:'Martinrea',mould:"",documents:""},
    {partnumber:['MX400607'], partName:'Housing DJ Capless DSL (Assembly)', partEcl:'1',customer:'Martinrea',mould:"",documents:""},
    {partnumber:['MX400608'], partName:'Housing DJ Capless DSL (Assembly)', partEcl:'2',customer:'Martinrea',mould:"",documents:""},


    {partnumber:['1133521'], partName:'A Pillar Wire Guide LH', partEcl:'A', customer:'Aptiv',mould:"TES9A",documents:""},
    {partnumber:['1133522'], partName:'A Pillar Wire Guide RH', partEcl:'A', customer:'Aptiv',mould:"TES9A",documents:""},
    {partnumber:['35253069'], partName:'A-pillar Lower Wire Guide LH', partEcl:'A',customer:'Aptiv',mould:"TES10B",documents:""},
    {partnumber:['35253050'], partName:'A-pillar Lower Wire Guide RH', partEcl:'A',customer:'Aptiv',mould:"TES10B",documents:""},


    {partnumber:['E15871'], partName:'Front MFB - CX430 RH', partEcl:'104', customer:'Brose',mould:"TB81944-02-003",documents:""},
    {partnumber:['E15872'], partName:'Front MFB - CX430 LH', partEcl:'104', customer:'Brose',mould:"TB81944-02-003",documents:""},
    {partnumber:['E15873'], partName:'Rear MFB - CX430 RH', partEcl:'103', customer:'Brose',mould:"18-391",documents:""},
    {partnumber:['E15874'], partName:'Rear MFB - CX430 LH', partEcl:'103', customer:'Brose',mould:"18-391",documents:""},
    {partnumber:['C47426'], partName:'Glass run channel LH', partEcl:'105', customer:'Brose',mould:"009-C19003-12",documents:""},
    {partnumber:['C47427'], partName:'Glass run channel RH', partEcl:'105', customer:'Brose',mould:"009-C19003-12",documents:""},
    {partnumber:['C47428'], partName:'Glass run channel LH', partEcl:'105', customer:'Brose',mould:"009-C19003-12",documents:""},
    {partnumber:['C47429'], partName:'Glass run channel RH', partEcl:'105', customer:'Brose',mould:"009-C19003-12",documents:""},
    {partnumber:['E59286'], partName:'P758 Front Multi-Function Bracket RH', partEcl:'101', customer:'Brose',mould:"",documents:""},
    {partnumber:['E59287'], partName:'P758 Front Multi-Function Bracket LH', partEcl:'101', customer:'Brose',mould:"",documents:""},
    {partnumber:['E59288'], partName:'P758 Rear Multi-Function Bracket RH', partEcl:'101', customer:'Brose',mould:"255",documents:""},
    {partnumber:['E59289'], partName:'P758 Rear Multi-Function Bracket LH', partEcl:'101', customer:'Brose',muld:"255",documents:""},


    {partnumber:['5Q0.501.733'], partName:'Underbody Shield LH', partEcl:'02S',customer:'VW',mould:"",documents:""},
    {partnumber:['5Q0.501.734'], partName:'Underbody Shield RH', partEcl:'02S',customer:'VW',mould:"",documents:""},
    {partnumber:['5WA.501.715.A'], partName:'Shielding', partEcl:'04S',customer:'VW',mould:"",documents:""},
    {partnumber:['5Q0.501.559 G'], partName:'Stoneguard LH', partEcl:'02S',customer:'VW',mould:"",documents:""},
    {partnumber:['5Q0.501.559 H'], partName:'Stoneguard LH', partEcl:'02S',customer:'VW',mould:"",documents:""},
    {partnumber:['5Q0.501.560 G'], partName:'Stoneguard RH', partEcl:'02S',customer:'VW',mould:"",documents:""},
    {partnumber:['5Q0.501.560 H'], partName:'Stoneguard RH', partEcl:'02S',customer:'VW',mould:"",documents:""},
    {partnumber:['5NN.825.215.B'], partName:'CD-Enhancing all wheel drive - Assy', partEcl:'03S',customer:'VW',mould:"VWM28-M01",documents:""},
    {partnumber:['5NA.980.815.A'], partName:'Camera fastener', partEcl:'05S',customer:'VW',mould:"",documents:""},
    {partnumber:['2GJ.825.205.A'], partName:'CD-Enhancing Underbody Panel - Assy', partEcl:'01S',customer:'VW',mould:"",documents:""},
    {partnumber:['2GJ.853.271B 2MG - FS'], partName:'Bright Fender Patch LH - FS', partEcl:'04S',customer:'VW',mould:"VW20-M01-A",documents:""},
    {partnumber:['2GJ.853.272B 2MG - FS'], partName:'Bright Fender Patch RH - FS', partEcl:'04S',customer:'VW',mould:"VW20-M01-A",documents:""},
    {partnumber:['2GJ.853.271B 2MG'], partName:'Bright Fender Patch Assembly LH', partEcl:'04S',customer:'VW',mould:"VW21-M02-A",documents:""},
    {partnumber:['2GJ.853.272B 2MG'], partName:'Bright Fender Patch Assembly RH', partEcl:'04S',customer:'VW',mould:"VW21-M02-A",documents:""},
    {partnumber:['2GJ.853.271 5AP - FS'], partName:'Fender Patch Assembly LH - FS', partEcl:'04S',customer:'VW',mould:"VW20-M01-A",documents:""},
    {partnumber:['2GJ.853.272 5AP - FS'], partName:'Fender Patch Assembly RH - FS', partEcl:'04S',customer:'VW',mould:"VW20-M01-A",documents:""},
    {partnumber:['2GJ.853.271 5AP'], partName:'Fender Patch Assembly LH', partEcl:'04S',customer:'VW',mould:"VW21-M02-A",documents:""},
    {partnumber:['2GJ.853.272 5AP'], partName:'Fender Patch Assembly RH', partEcl:'04S',customer:'VW',mould:"VW21-M02-A",documents:""},
    {partnumber:['575.819.676'], partName:'Acoustic Box', partEcl:'02S',customer:'VW',mould:"VW18-M01",documents:""},
    {partnumber:['2GG.821.111 - FS'], partName:'Endplate Fender LH - FS', partEcl:'04S',customer:'VW',mould:"VW-M01-A",documents:""},
    {partnumber:['2GG.821.112 - FS'], partName:'Endplate Fender RH - FS', partEcl:'04S',customer:'VW',mould:"VW-M01-A",documents:""},
    {partnumber:['2GG.821.111'], partName:'Endplate Fender LH', partEcl:'04S',customer:'VW',mould:"VW-M01-A",documents:""},
    {partnumber:['2GG.821.112'], partName:'Endplate Fender RH', partEcl:'04S',customer:'VW',mould:"VW-M01-A",documents:""},
    {partnumber:['575.839.613'], partName:'Guide Rail LH', partEcl:'02S',customer:'VW', mould:"VW-17 MO1",documents:""},
    {partnumber:['575.839.614'], partName:'Guide Rail RH', partEcl:'02S',customer:'VW', mould:"VW-17 MO1",documents:""},




    {partnumber:['1494185-00-C'], partName:'Front Fender Garnish, LH ASY, MY', partEcl:'C',customer:'Tesla',mould:"TES24-MO1-A",documents:""},
    {partnumber:['1494186-00-C'], partName:'Front Fender Garnish, RH ASY, MY', partEcl:'C',customer:'Tesla',mould:"TES24-MO1-A",documents:""},
    {partnumber:['1494187-00-C'], partName:'Rear Fender Garnish, LH ASY, MY', partEcl:'C',customer:'Tesla',mould:"TES25-MO1-A",documents:""},
    {partnumber:['1494188-00-C'], partName:'Rear Fender Garnish, RH ASY, MY', partEcl:'C',customer:'Tesla',mould:"TES25-MO1-A",documents:""},
    {partnumber:['1619812-00-B'], partName:'Rear Apron, HEPA, MY', partEcl:'B',customer:'Tesla',mould:"TES 25-M01-A",documents:""},
    {partnumber:['1584746-00-A'], partName:'MS P2 FR Closeout Panel Assy RH', partEcl:'A',customer:'Tesla',mould:"TES-44-M01-A",documents:""},
    {partnumber:['1584749-00-A'], partName:'MS P2 FR Closeout Panel Assy LH', partEcl:'A',customer:'Tesla',mould:"TES-44-M01-A",documents:""},
    {partnumber:['1584797-00-A'], partName:'MS P2 RR Closeout Panel Assy LH', partEcl:'A',customer:'Tesla',mould:"TES-43-M01-A",documents:""},
    {partnumber:['1584798-00-A'], partName:'MS P2 RR Closeout Panel Assy RH', partEcl:'A',customer:'Tesla',mould:"TES-43-M01-A",documents:""},
    {partnumber:['1492603-00-D'], partName:'Model Y, Colw Screen ASY', partEcl:'D',customer:'Tesla',mould:"Tesla 26-M018",documents:""},
    {partnumber:['1564256-00-A'], partName:'MS P2 Frunk Access Panel ASSY', partEcl:'A',customer:'Tesla',mould:"TES 47-M01",documents:""},
    {partnumber:['1494086-00-B'], partName:'ASY, Access Panel, Model Y', partEcl:'B',customer:'Tesla',mould:"TES-28-M01-A",documents:""},
    {partnumber:['1092146-00-D'], partName:'M3S FR LH Closeout Panel ASSY', partEcl:'D',customer:'Tesla',mould:"TES5D",documents:""},
    {partnumber:['1092147-00-D'], partName:'M3S FR RH Closeout Panel ASSY', partEcl:'D',customer:'Tesla',mould:"TES5D",documents:""},
    {partnumber:['1494933-00-B'], partName:'3inX 1R Riser Cover LH', partEcl:'B',customer:'Tesla',mould:"TES 29",documents:""},
    {partnumber:['1494934-00-B'], partName:'3inX 1R Riser Cover RH', partEcl:'B',customer:'Tesla',mould:"TES 29",documents:""},
    {partnumber:['1494935-00-B'], partName:'3inX 1R Cover Podium LHS INR LH', partEcl:'B',customer:'Tesla',mould:"TES 30",documents:""},
    {partnumber:['1624936-00-A'], partName:'3inX 1R Cover Podium LHS INR RH', partEcl:'A',customer:'Tesla',mould:"TES 31",documents:""},
    {partnumber:['1624937-00-A'], partName:'3inX 1R Cover Podium RHS INR LH', partEcl:'A',customer:'Tesla',mould:"TES 31",documents:""},
    {partnumber:['1494938-00-B'], partName:'3inX 1R Cover Podium RHS INR RH', partEcl:'B',customer:'Tesla',mould:"TES 30",documents:""},
    {partnumber:['1584751-00-A'], partName:'MS P2 FR Grab Handle', partEcl:'A',customer:'Tesla',mould:"TES-45-M01-A",documents:""},
    {partnumber:['1584795-00-A'], partName:'MS P2 RR Grab Handle LH', partEcl:'A',customer:'Tesla',mould:"TES-45-M01-A",documents:""},
    {partnumber:['1584796-00-A'], partName:'MS P2 RR Grab Handle RH', partEcl:'A',customer:'Tesla',mould:"TES-45-M01-A",documents:""},
    {partnumber:['1107204-00-E'], partName:'Inner Duct HVAC Plenum M3', partEcl:'E',customer:'Tesla',mould:"TES-8D",documents:""},
    {partnumber:['1470967-00-B'], partName:'M3 Trunk LD FLR SPPRT Bracket LH', partEcl:'B',customer:'Tesla',mould:"TES14-E",documents:""},
    {partnumber:['1470963-00-B'], partName:'M3 Trunk LD FLR SPPRT Bracket RH', partEcl:'B',customer:'Tesla',mould:"TES14-E",documents:""},


    {partnumber:['744.846750_00'], partName:'Front Part Waterchannel ASY', partEcl:'0',customer:'CIE',mould:"",documents:""},


    {partnumber:['57008758AB'], partName:'DJ Access Cover', partEcl:'4',customer:'Stellantis',mould:"",documents:""},
];
module.exports = dataParts;