// utils/emailTemplates.js

const templateApgGreen = () => {
    return {
        subject: "RV: ¡APG Green! 🍃",
        text: "DO NOT REPLY BACK this email - Autogenerated\n\n¡Ahorrar energía y cuidar el medio ambiente, es tarea de todos!",
        html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto;">
                <p style="color: #666; font-size: 12px; font-weight: bold;">
                    DO NOT REPLY BACK this email - Autogenerated
                </p>
                <img src="https://paperless-apg.s3.us-east-1.amazonaws.com/apg-green.jpg" alt="APG Green" style="width: 100%; height: auto; border-radius: 8px;">
            </div>
        `
    };
};

const templatePausaActiva = () => {
    return {
        subject: "RV: ¡Es momento de hacer tu pausa activa! 🧘‍♂️",
        text: "DO NOT REPLY BACK this email - Autogenerated\n\nRompe la rutina y dedícale tiempo a tu bienestar.",
        html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto;">
                <p style="color: #666; font-size: 12px; font-weight: bold;">
                    DO NOT REPLY BACK this email - Autogenerated
                </p>
                <p style="color: #333; font-size: 14px;">
                    Rompe la rutina y dedícale tiempo a tu bienestar.
                </p>
                <img src="https://paperless-apg.s3.us-east-1.amazonaws.com/pausa-activa.jpg" alt="Pausa Activa" style="width: 100%; height: auto; border-radius: 8px;">
            </div>
        `
    };
};

module.exports = {
    templateApgGreen,
    templatePausaActiva
};